name: Gym Number Scraper

# Schedule the job to run every 15 minutes
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run the scraper
      run: |
        python gym_nbr.py

    - name: Commit and push the CSV file back to the repository
      run: |
        git config --global user.email "y.graedel@gmail.com"
        git config --global user.name "graeyv"
        git add scraped_data.csv
        git commit -m "Update scraped data"
        git pull
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This will automatically use a GitHub-provided token
